# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import window_control_pb2 as window__control__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in window_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WindowControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/winp.agent.v1.WindowControlService/Health',
                request_serializer=window__control__pb2.Empty.SerializeToString,
                response_deserializer=window__control__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.StreamWindows = channel.unary_stream(
                '/winp.agent.v1.WindowControlService/StreamWindows',
                request_serializer=window__control__pb2.StreamWindowsRequest.SerializeToString,
                response_deserializer=window__control__pb2.WindowEvent.FromString,
                _registered_method=True)
        self.MoveResize = channel.unary_unary(
                '/winp.agent.v1.WindowControlService/MoveResize',
                request_serializer=window__control__pb2.MoveResizeRequest.SerializeToString,
                response_deserializer=window__control__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.Focus = channel.unary_unary(
                '/winp.agent.v1.WindowControlService/Focus',
                request_serializer=window__control__pb2.FocusRequest.SerializeToString,
                response_deserializer=window__control__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/winp.agent.v1.WindowControlService/Close',
                request_serializer=window__control__pb2.CloseRequest.SerializeToString,
                response_deserializer=window__control__pb2.ControlResponse.FromString,
                _registered_method=True)


class WindowControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWindows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveResize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Focus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WindowControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=window__control__pb2.Empty.FromString,
                    response_serializer=window__control__pb2.HealthResponse.SerializeToString,
            ),
            'StreamWindows': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWindows,
                    request_deserializer=window__control__pb2.StreamWindowsRequest.FromString,
                    response_serializer=window__control__pb2.WindowEvent.SerializeToString,
            ),
            'MoveResize': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveResize,
                    request_deserializer=window__control__pb2.MoveResizeRequest.FromString,
                    response_serializer=window__control__pb2.ControlResponse.SerializeToString,
            ),
            'Focus': grpc.unary_unary_rpc_method_handler(
                    servicer.Focus,
                    request_deserializer=window__control__pb2.FocusRequest.FromString,
                    response_serializer=window__control__pb2.ControlResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=window__control__pb2.CloseRequest.FromString,
                    response_serializer=window__control__pb2.ControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'winp.agent.v1.WindowControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('winp.agent.v1.WindowControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WindowControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/winp.agent.v1.WindowControlService/Health',
            window__control__pb2.Empty.SerializeToString,
            window__control__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamWindows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/winp.agent.v1.WindowControlService/StreamWindows',
            window__control__pb2.StreamWindowsRequest.SerializeToString,
            window__control__pb2.WindowEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveResize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/winp.agent.v1.WindowControlService/MoveResize',
            window__control__pb2.MoveResizeRequest.SerializeToString,
            window__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Focus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/winp.agent.v1.WindowControlService/Focus',
            window__control__pb2.FocusRequest.SerializeToString,
            window__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/winp.agent.v1.WindowControlService/Close',
            window__control__pb2.CloseRequest.SerializeToString,
            window__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
